##Task 1 – Linear Algebra Implementation

In [ ]:
import numpy as np

vector_a = np.array([2, 4, 6])
vector_b = np.array([1, 3, 5])
matrix_a = np.array([
    [2, 1, 3],
    [1, 0, 2],
    [4, 1, 1]
])
matrix_b = np.array([
    [1, 2, 0],
    [3, 1, 4],
    [2, 5, 1]
])

print("Vector Addition:", vector_a + vector_b)
print("Vector Subtraction:", vector_a - vector_b)
print("Dot Product:", np.dot(vector_a, vector_b))

print("\nMatrix Addition:\n", matrix_a + matrix_b)
print("\nMatrix Multiplication:\n", matrix_a @ matrix_b)

det_a = np.linalg.det(matrix_a)
print("\nDeterminant of matrix_a:", det_a)

if not np.isclose(det_a, 0):
    inv_a = np.linalg.inv(matrix_a)
    print("\nInverse of matrix_a:\n", inv_a)
else:
    print("Matrix is singular; inverse does not exist.")

eigenvalues, eigenvectors = np.linalg.eig(matrix_a)
print("\nEigenvalues:", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Vector Addition: [ 3  7 11]
Vector Subtraction: [1 1 1]
Dot Product: 44

Matrix Addition:
 [[3 3 3]
 [4 1 6]
 [6 6 2]]

Matrix Multiplication:
 [[11 20  7]
 [ 5 12  2]
 [ 9 14  5]]

Determinant of matrix_a: 6.0

Inverse of matrix_a:
 [[-0.33333333  0.33333333  0.33333333]
 [ 1.16666667 -1.66666667 -0.16666667]
 [ 0.16666667  0.33333333 -0.16666667]]

Eigenvalues: [ 5.54138127 -2.         -0.54138127]

Eigenvectors:
 [[-0.66037269 -0.42163702  0.17485589]
 [-0.3575134  -0.52704628 -0.96894315]
 [-0.66037269  0.73786479  0.17485589]]


##Task 2 – Probability Concepts

In [ ]:
sales_success = [0.65, 0.35]
customer_segments = ["Premium", "Regular"]
segment_purchase_probability = {
"Premium": 0.80,
"Regular": 0.50
}

In [ ]:
import numpy as np

sales_success = [0.65, 0.35]
customer_segments = ["Premium", "Regular"]

segment_purchase_probability = {
    "Premium": 0.80,
    "Regular": 0.50
}

probability_success = sum(sales_success[i] * segment_purchase_probability[customer_segments[i]]for i in range(len(customer_segments)))

print("Probability of successful sales:", probability_success)
print(f'')
print("Percentage:", probability_success * 100, "%")

p_purchase_given_premium = segment_purchase_probability["Premium"]
p_purchase_given_regular = segment_purchase_probability["Regular"]
print(f'')
print("p_purchase_given_premium", p_purchase_given_premium)
print(f'')
print("p_purchase_given_regular", p_purchase_given_regular)

Probability of successful sales: 0.6950000000000001

Percentage: 69.5 %

p_purchase_given_premium=> 0.8

p_purchase_given_regular=> 0.5


###Apply Bayes Theorem

In [ ]:
P_A = 0.40
P_B = 0.62
P_B_given_A = 0.80
P_A_given_B = (P_B_given_A * P_A) / P_B

print("P_A_given_B", P_A_given_B)
print(f'')
print("Updated probability:", P_A_given_B * 100, "%")

P_A_given_B 0.5161290322580646

Updated probability: 51.61290322580646 %


###Simulate Binomial Distribution - 20 trials

In [ ]:
n_trials = 20
success_prob = 0.65

result = np.random.binomial(
    n=n_trials,
    p=success_prob,
    size=20
)
P_A_given_B
print("Binomial distribution - 20 trials")
P_A_given_B
print(result)

Binomial distribution - 20 trials
[13 12 15 10 10 11 16  7 12 13 14 14 13 18 13 14 13 14 11 14]


###Generate a normal distribution and uniform distribution

In [ ]:
normal_mean = 50
normal_std = 10
uniform_low = 0
uniform_high = 1

normal_data = np.random.normal(loc=normal_mean,scale=normal_std,size=1000)
uniform_data = np.random.uniform(low=uniform_low,high=uniform_high,size=1000)
print(f"")
print("Normal Distribution")
print(f"")
print(normal_data)
print(f"")
print("Uniform Distribution")
print(f"")
print(uniform_data)


Normal Distribution

[51.12438715 42.43568828 53.95916808 73.43754158 49.34602592 45.45978678
 62.84122198 36.60750207 28.3669998  46.95350665 63.38379261 54.48266797
 58.89017022 35.56439078 34.24215058 31.36167969 42.67311423 49.04132312
 59.93877637 39.69058678 45.3064112  62.9317884  35.53723572 54.59516442
 48.38738873 46.09372771 55.83826394 51.22301905 43.34180186 50.11241217
 43.92691021 46.32475346 46.50207417 31.22053773 71.64037546 55.617484
 49.96561722 55.38494977 60.42140668 40.22386271 47.82906691 30.64037287
 52.76403694 56.17031748 36.78730125 62.24366028 40.81983886 53.78297027
 53.85745125 42.12553194 40.26481462 47.58425764 34.89774593 57.07228051
 57.80616383 41.84970664 58.56539773 48.1328226  39.21561742 51.59518607
 41.81971999 39.54313357 64.20741094 57.05200177 57.14680525 55.5212311
 58.40104081 51.88194999 40.59895777 55.18470884 51.2708134  29.50683367
 44.57140667 49.20475118 53.23224962 52.46761959 50.65719141 39.79827452
 58.38307658 41.67259885 48.1888

#Task 3 – Descriptive Statistics

In [ ]:
import numpy as np
import pandas as pd
import statistics

sales_data = [
    120, 135, 150, 145, 160, 155, 170, 165, 180, 175,
    190, 200, 210, 195, 185, 175, 165, 155, 145, 135
]


mean_value = np.mean(sales_data)
median_value = np.median(sales_data)
mode_value = statistics.mode(sales_data)
sales_range = np.max(sales_data) - np.min(sales_data)
variance = np.var(sales_data)
standard_deviation = np.std(sales_data)
print(f"")
print("Mean", mean_value)
print(f"")
print("Median", median_value)
print(f"")
print("Mode", mode_value)
print(f"")

print("Range", sales_range)
print(f"")
print("Variance", variance)
print(f"")
print("Standard Deviation", standard_deviation)
print(f"")

sales = pd.Series(sales_data)
skewness = sales.skew()
kurtosis = sales.kurt()
print(f"")
print("Skewness", skewness)
print(f"")
print("Kurtosis", kurtosis)
print(f"")


Mean 165.5

Median 165.0

Mode 135

Range 90

Variance 534.75

Standard Deviation 23.124662159694356


Skewness 0.03264455519886574

Kurtosis -0.5493161347714888



**Interpret about dataset**

The sales dataset is approximately symmetric, because its skewness is very close to zero. The slight negative value indicates a very weak negative skew, but it is not substantial enough to consider the dataset strongly negatively skewed.